apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: pranor-vault-io-latency
  namespace: default
spec:
  action: mixed
  mode: one
  selector:
    labelSelectors:
      'app.kubernetes.io/name': 'pranor-vault'
  volumeMountPath: /data
  delay:
    read: '500ms'
    write: '500ms'
  errno: 5 # EIO input/output error
  percent: 10
  duration: '5m'
  scheduler:
    cron: '*/20 * * * *'
