apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pranor-vault-pod-failure
  namespace: default
spec:
  action: pod-failure
  mode: one
  duration: '5m'
  selector:
    labelSelectors:
      'app.kubernetes.io/name': 'pranor-vault'
  scheduler:
    cron: '*/10 * * * *'
