package import (
	"fmt"
	"strings"
)

// PythonCodeGenerator translates Pranor AST struct definitions into Python dataclasses / Pydantic models.
type PythonCodeGenerator struct{}

// NewPythonCodeGenerator creates a PythonCodeGenerator instance.
func NewPythonCodeGenerator() *PythonCodeGenerator {
	return &PythonCodeGenerator{}
}

// GeneratePython generates Python code string from Pranor struct definitions.
func (pcg *PythonCodeGenerator) GeneratePython(structs []StructDef) string {
	var sb strings.Builder

	sb.WriteString("# Code generated by Pranor (target: Python). DO NOT EDIT.\n")
	sb.WriteString("from dataclasses import dataclass\n")
	sb.WriteString("from typing import Optional, List, Dict, Any\n\n\n")

	for _, s := range structs {
		sb.WriteString("@dataclass\n")
		sb.WriteString(fmt.Sprintf("class %s:\n", s.Name))

		if len(s.Fields) == 0 {
			sb.WriteString("    pass\n\n")
			continue
		}

		for _, f := range s.Fields {
			pyType := mapToPythonType(f.Type)
			if f.Optional {
				pyType = fmt.Sprintf("Optional[%s] = None", pyType)
			}
			sb.WriteString(fmt.Sprintf("    %s: %s\n", toSnakeCase(f.Name), pyType))
		}
		sb.WriteString("\n")
	}

	return sb.String()
}

func mapToPythonType(servType string) string {
	switch strings.ToLower(servType) {
	case "string":
		return "str"
	case "int", "int32", "int64":
		return "int"
	case "float", "float64":
		return "float"
	case "bool", "boolean":
		return "bool"
	default:
		return servType
	}
}


