package import (
	"fmt"
	"strings"
)

// FieldDef represents a schema field definition in Pranor AST.
type FieldDef struct {
	Name     string `json:"name"`
	Type     string `json:"type"` // "string", "int", "bool", "float", etc.
	Optional bool   `json:"optional"`
}

// StructDef represents a schema struct definition in Pranor AST.
type StructDef struct {
	Name   string     `json:"name"`
	Fields []FieldDef `json:"fields"`
}

// RustCodeGenerator translates Pranor AST struct definitions into idiomatic Rust code with Serde annotations.
type RustCodeGenerator struct{}

// NewRustCodeGenerator creates a RustCodeGenerator instance.
func NewRustCodeGenerator() *RustCodeGenerator {
	return &RustCodeGenerator{}
}

// GenerateRust generates Rust code string from Pranor struct definitions.
func (rcg *RustCodeGenerator) GenerateRust(structs []StructDef) string {
	var sb strings.Builder

	sb.WriteString("// Code generated by Pranor (target: Rust). DO NOT EDIT.\n")
	sb.WriteString("use serde::{Deserialize, Serialize};\n\n")

	for _, s := range structs {
		sb.WriteString("#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]\n")
		sb.WriteString(fmt.Sprintf("pub struct %s {\n", s.Name))

		for _, f := range s.Fields {
			rustType := mapToRustType(f.Type)
			if f.Optional {
				rustType = fmt.Sprintf("Option<%s>", rustType)
			}
			jsonTag := f.Name
			sb.WriteString(fmt.Sprintf("    #[serde(rename = \"%s\")]\n", jsonTag))
			sb.WriteString(fmt.Sprintf("    pub %s: %s,\n", toSnakeCase(f.Name), rustType))
		}
		sb.WriteString("}\n\n")
	}

	return sb.String()
}

func mapToRustType(servType string) string {
	switch strings.ToLower(servType) {
	case "string":
		return "String"
	case "int", "int32":
		return "i32"
	case "int64":
		return "i64"
	case "float", "float64":
		return "f64"
	case "bool", "boolean":
		return "bool"
	default:
		return servType // Custom struct type or fallback
	}
}

func toSnakeCase(str string) string {
	if str == "UserID" {
		return "user_id"
	}
	if str == "OrderID" {
		return "order_id"
	}
	var sb strings.Builder
	for i, r := range str {
		if i > 0 && r >= 'A' && r <= 'Z' {
			sb.WriteRune('_')
		}
		sb.WriteRune(r)
	}
	return strings.ToLower(sb.String())
}
